couchpotato:
  image: jbogatay/couchpotato
  restart: unless-stopped
  ports:
    - "5050:5050"
  container_name: couchpotato
  environment:
    - PUID=1001
    - PGID=1001
    - TZ=America/Detroit
  volumes:
    - /home/media/.config/couchpotato:/config
    - /home/media/video/movies:/movies
    - /home/media/video/in/movies:/downloads
    - /home/media/blackhole-out/movies:/blackhole
