#!/usr/bin/with-contenv bash

mkdir -p /var/log/couchpotato

# install app
[[ ! -d "/app/couchpotato/.git" ]] && \
  git clone https://github.com/CouchPotato/CouchPotatoServer /app/couchpotato

chown -R abc:abc /app
chown -R abc:abc /config

chmod 777 /var/log/couchpotato